language: r

sudo: required

install:
  - ./travis-tool.sh github_package jimhester/covr

after_success:
  - Rscript -e 'covr::coveralls()'

notifications:
  email:
    on_success: change
    on_failure: always